config/routes.rb
Rails.application.routes.draw do

    resources :categories
    resources :saved_gems
    resources :users

      resources :city_gems do
        resources :likes
        resources :comments
      end


    root 'login#new'

    get '/login', to: 'login#new'
    post '/login', to: 'login#create'
    delete '/logout', to: 'login#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :city_gems
end

app/models/city_gem.rb
class CityGem < ApplicationRecord
  has_many :comments
  has_many :saved_gems
  has_many :users, through: :likes
  has_many :likes, dependent: :destroy
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :city_gem
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :city_gem

end

app/models/saved_gem.rb
class SavedGem < ApplicationRecord
  belongs_to :user
  belongs_to :city_gem
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :comments
  has_many :saved_gems
  has_many :likes, dependent: :destroy
  has_many :city_gems, through: :likes

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_city_gem
  before_action :find_like, only: [:destroy]

   def index
     redirect_to city_gem_path(@city_gem)
   end

    def create
      if already_liked?
        flash[:notice] = "You can't like more than once"
      else
        @city_gem.likes.create(user_id: current_user)
      end
        redirect_to city_gem_path(@city_gem)
    end

    def destroy
      if !(already_liked?)
        flash[:notice] = "Cannot unlike"
    else
        @like.destroy
    end
        redirect_to city_gem_path(@city_gem)
    end

    def find_like
      @like = @city_gem.likes.find(params[:id])
    end


    private

    def find_city_gem
      @city_gem = CityGem.find(params[:city_gem_id])
    end

    def already_liked?
      Like.where(user_id: current_user, city_gem_id:
      params[:city_gem_id]).exists?
    end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      # redirect_to :root
      redirect_to user_path(@user)
    else
      flash[:error] = "Please try again or create a user, what you entered was not valid."
      flash.discard(:error)
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
    def set_user
    @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:name, :email, :img_url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path(@user)
    else
      flash[:error] = "We couldn't save your user."
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path(@user)
    else
      render :edit
    end
  end

  private
    def set_user
    @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:name, :email, :username, :img_url)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/city_gem_helper.rb
module CityGemHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/saved_gem_helper.rb
module SavedGemHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Trings</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNav">
     <ul class="navbar-nav">
       <li class="nav-item active">
         <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item">
          
         <a class="nav-link" href="/users/<%= current_user %>">Profile</a>

       </li>
       <li class="nav-item">
         <a class="nav-link" href="/city_gems/">City Gem</a>
       </li>
       <nav>
         <% if current_user %>
           <%= link_to("Logout", logout_path, method: :delete) %>
         <% else %>
           <%= link_to("Login", login_path) %> |
           <%= link_to("Signup", new_user_path) %>
         <% end %>
       </nav>
     </ul>
   </div>
  </nav>



    <% if flash[:error] %>
      <p style="color: red">
        <%= flash[:error] %>
      </p>
    <% elsif flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>